# Generated by Django 5.1.4 on 2025-01-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Софт', 'verbose_name_plural': 'Софты'},
        ),
        migrations.AddField(
            model_name='articles',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
    ]
