# Generated by Django 5.1.4 on 2025-01-17 14:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_articles_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
    ]
